# Generated by Django 5.1.3 on 2024-11-19 14:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('activity_name', models.CharField(default='Activity', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('organizer_name', models.CharField(default='Name', max_length=255)),
                ('organizer_address', models.CharField(max_length=255, null=True)),
                ('external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('name', models.CharField(default='Name', max_length=255)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='activity_bookings',
            fields=[
                ('activitybooking_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('booking_date', models.DateField(null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='centralbookings.activity')),
            ],
        ),
        migrations.CreateModel(
            name='activity_hosting',
            fields=[
                ('hosting_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('expected_participants', models.IntegerField(null=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='centralbookings.activity')),
            ],
        ),
        migrations.CreateModel(
            name='contact_person',
            fields=[
                ('contactperson_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('contact_name', models.CharField(default='Name', max_length=255)),
                ('contact_email', models.CharField(max_length=255, null=True)),
                ('contact_phone_number', models.CharField(default='000000000000000', max_length=15)),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='centralbookings.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('address_line1', models.CharField(default='Line 1', max_length=255)),
                ('city', models.CharField(default='City', max_length=255)),
                ('region', models.CharField(default='Region', max_length=255)),
                ('country', models.CharField(default='Country', max_length=255)),
                ('organizer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='centralbookings.organizer')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='centralbookings.organizer'),
        ),
        migrations.CreateModel(
            name='participant_type',
            fields=[
                ('participanttype_no', models.AutoField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999), django.core.validators.MinLengthValidator(6)])),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='centralbookings.participant')),
            ],
        ),
    ]
